name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    # Set up operating system
    runs-on: ubuntu-latest
    steps:
    # Step 1. Set up Python 3.9
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    # Step 2. Check-out repository so we can access its contents
    - uses: actions/checkout@v2
    # Step 3. Install poetry
    - uses: snok/install-poetry@v1
    # Step 4. Install our package
    - name: Install package
      run: poetry install
    # Step 5. Run tests for package
    - name: Test with pytest
      run: poetry run pytest tests/ --cov={{ cookiecutter.package_name }} --cov-report=xml
    # Step 6. Use Codecov to track coverage
    - uses: codecov/codecov-action@v2
      with:
        files: ./coverage.xml   # coverage report
        fail_ci_if_error: true  # terminate workflow if there's an error
    # Step 7. Build documentation
    - name: Build documentation
      run: poetry run make html --directory docs/
